
SELECT *  FROM  HR.LOCATIONS NATURAL JOIN  HR.COUNTRIES;


SELECT *  FROM  HR.LOCATIONS  JOIN  HR.COUNTRIES
USING(COUNTRY_ID);

SELECT *  FROM  HR.LOCATIONS L JOIN  HR.COUNTRIES C 
ON L.COUNTRY_ID = C.COUNTRY_ID ;

SELECT *  FROM  HR.LOCATIONS L inner join  HR.COUNTRIES C 
ON L.COUNTRY_ID = C.COUNTRY_ID ;

SELECT *  FROM  HR.LOCATIONS L LEFT OUTER join  HR.COUNTRIES C 
ON L.COUNTRY_ID = C.COUNTRY_ID ;

SELECT *  FROM  HR.LOCATIONS L right join  HR.COUNTRIES C 
ON L.COUNTRY_ID = C.COUNTRY_ID ;

SELECT *  FROM  HR.LOCATIONS L FULL OUTER join  HR.COUNTRIES C 
ON L.COUNTRY_ID = C.COUNTRY_ID ;




