
SELECT *  FROM  HR.JOBS NATURAL JOIN  HR.JOB_HISTORY;


SELECT *  FROM  HR.JOBS  JOIN  HR.JOB_HISTORY
USING(JOB_ID);

SELECT *  FROM  HR.JOBS g JOIN  HR.JOB_HISTORY h 
ON   g.JOB_ID = h.JOB_ID ;

SELECT *  FROM  HR.JOBS g inner  JOIN  HR.JOB_HISTORY h 
ON   g.JOB_ID = h.JOB_ID ;

SELECT *  FROM  HR.JOBS g LEFT JOIN  HR.JOB_HISTORY h 
ON   g.JOB_ID = h.JOB_ID ;

SELECT *  FROM  HR.JOBS g right  JOIN  HR.JOB_HISTORY h 
ON   g.JOB_ID = h.JOB_ID ;

SELECT *  FROM  HR.JOBS g FULL JOIN  HR.JOB_HISTORY h 
ON   g.JOB_ID = h.JOB_ID ;






