
CREATE TABLE STUDENT_DB (ID NUMBER(12) , NAME VARCHAR2(20));


INSERT INTO STUDENT_DB VALUES (1 ,'AHMED');

SELECT * FROM STUDENT_DB;

UPDATE STUDENT_DB SET ID = 10 , NAME= 'OMAR';

DELETE STUDENT_DB WHERE ID = 1;

DROP TABLE STUDENT_DB;