SELECT * FROM employees WHERE EMPLOYEE_ID BETWEEN 100 AND 105;
SELECT * FROM employees WHERE EMPLOYEE_ID BETWEEN 151 AND 155;
SELECT * FROM employees WHERE FIRST_NAME LIKE 'p%' OR FIRST_NAME LIKE 'P%' ;
SELECT * FROM employees WHERE FIRST_NAME LIKE '%a' OR FIRST_NAME LIKE '%A' ;
SELECT * FROM employees WHERE FIRST_NAME LIKE '%a' OR FIRST_NAME LIKE '%A%' OR FIRST_NAME LIKE '%a%' ;
SELECT * FROM employees WHERE FIRST_NAME LIKE '__e%' OR FIRST_NAME LIKE '__E%' ;
SELECT * FROM employees WHERE MANAGER_ID  IS NULL;
SELECT * FROM employees WHERE MANAGER_ID  IS NOT NULL;

INSERT INTO employees (EMPLOYEE_ID ,FIRST_NAME , LAST_NAME, EMAIL,PHONE_NUMBER ,JOB_ID ,SALARY, HIRE_DATE , DEPARTMENT_ID )
VALUES (207 ,'AHMED' ,'MOHAMED' , 'Egypt' ,'010614548', 'IT_PROG' , 31999  , sysdate  );

UPDATE employees SET DEPARTMENT_ID = 80 WHERE EMPLOYEE_ID = 207;

SELECT * FROM employees ORDER BY HIRE_DATE DESC ; 

SELECT * FROM employees ORDER BY DEPARTMENT_ID ASC , SALARY DESC ;

SELECT LOWER(LAST_NAME ) FROM employees ;
SELECT UPPER(FIRST_NAME ) FROM employees ;

SELECT CONCAT(INITCAP(FIRST_NAME ||' ') , INITCAP(LAST_NAME)) full_Name FROM employees;

SELECT * FROM employees WHERE LAST_NAME = 'smith';






	